/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class ECommerceApp {
    // Create a regular user and a premium user
    User regularUser = new User("Alice", "regular");
    User premiumUser = new User("Bob", "premium");

    // Create some products
    Product product1 = new Product("Laptop", 1000);
    Product product2 = new Product("Headphones", 200);

    
}
